### ISSUE TITLE
duplicate data_names for every data source 

### ISSUE THREAD

**Issue by ankitjain-splunk** [guilhemmarchand/trackme#102]
I'm having an issue in my environment where every data source is duplicated in the "Data Sources Availability Tracking" page. I was originally running 1.1.11 and now I'm running 1.1.16 which is having the same issue. 

What appears to be happening is that when I run the reset collection mechanism, it will compile the list correctly once, and then after a few minutes it will append and update the second data_name. 

I haven't tried uninstalling and reinstalling the app, or clearing the collections manually. I was wondering if there was a simpler fix or if this was a known issue. I'm happy to provide screenshots and more troubleshooting I have done over Slack.

Below is a snippet for just one index/sourcetype filter. That date of 6/24 14:44 on the bottom row is around when I reset the collection. 

![image001](https://user-images.githubusercontent.com/41373403/85775263-9fa33880-b6ed-11ea-86e6-10027e284411.png)

**Comment by guilhemmarchand** [comment]
Hi @ankitjain-splunk 

Right this technically should not be happening anymore since Version 1.2.x but I will double check if there is something to be improved and better protected when one resets the collection.

Since version 1.2.x records are managed by their internal _key via insert / update rather than full flush like it used to be.

To fix your immediate issue you can do:

`| inputlookup trackme_data_source_monitoring
| eval _time=data_tracker_runtime 
| stats latest(*) as "*" by data_name
| outputlookup trackme_data_source_monitoring`

And the same can be done for hosts too if same issue happened:

`| inputlookup trackme_host_monitoring
| eval _time=data_tracker_runtime 
| stats latest(*) as "*" by data_host
| outputlookup trackme_host_monitoring`

Let me know if this fixes your issue.

Guilhem

**Comment by ankitjain-splunk** [comment]
Thank you for the quick reply. That search was able to repair the issue and I'm going to let it sit to see if it's resilient overnight. Interestingly, this issue didn't seem to happen for hosts.

I haven't updated to 1.2.x yet because I'm a little hesitant to use summary indexing in our environment in the near-term. Right now I'm trying to demonstrate to my customer that this solution will meet their goals, which I'm sure it will :) 

Great work on this app. I appreciate all the hard work that went into it.

**Comment by guilhemmarchand** [comment]
Thanks @ankitjain-splunk ;-)

Good, if an issue would happen it would happen quite quickly between the short term tracker execution (every 5 min) and the long term (once per hour) but this shouldn't be the case.

No problem, the version 1.2.x is behaving better than 1.0.x and faster, with shorter run time of the trackers and of course many things improved and fixed obviously.
Efforts have been achieved to support better very high scale environment but it's up to you no problem, I would suggest to create now the indexes required for the 1.2.x such that you can update smoothly when you wish to so do.

Gulhem

**Comment by guilhemmarchand** [comment]
I assume we can close this issue @ankitjain-splunk 

Let me know otherwise.

Guilhem
