### ISSUE TITLE
Enhancement, Index macro definition based on lookup

### ISSUE THREAD

**Issue by mljdivemaster** [guilhemmarchand/trackme#28]
The search macro [trackme_idx_filter] is based on a host filter. Can it based on a lookup?

Like this:

[| inputlookup splunkref
| search function="Index*"
| eval host=fqdn
| table host]

**Comment by guilhemmarchand** [comment]
Yes, the macro does currently:

```
# defined pattern filter for indexers
[trackme_idx_filter]
definition = host=idx*
iseval = 0
```

It is being in searches similar to this:

```
(index=_internal `trackme_idx_filter` source=*metrics.log sourcetype=splunkd group=queue name IN(\"tcpin_cooked_pqueue\"))
```

As long as the macro returns the list of host that represent the indexers (host=foo OR host=bar), the searches will work just fine.

I suppose you are asking for the definition to based by default on a lookup rather than a filter, or you are happy with user customisation ?

**Comment by mljdivemaster** [comment]
No, user customisation works fine!
