### ISSUE TITLE
Trackme, how to change default priorities based on a tag

### ISSUE THREAD

**Issue by 11gods** [guilhemmarchand/trackme#281]
Hi, 

We would like to classify different data sources based on tags. Can we set a priority based on a tag?

As well can we create a tag based on a regex for hosts?

Thanks

**Comment by guilhemmarchand** [comment]
Yes @11gods  please, this would be lovely ;-)

**Comment by guilhemmarchand** [comment]
@11gods 

I have been thinking about this one, regarding tags for host (data and metric hosts)

I do now remember why I didn't consider it, I didn't because there another form of "tags" feature for the data hosts and metrics hosts, which relies on lookup feature against a CMDB data (Assets from ES or anything else) in a CIM like concept.

https://trackme.readthedocs.io/en/latest/configuration.html#step-5-host-tags-enrichment

Data sources are different conceptually speaking given that these aren't properly endpoints for instance, so you will likely not have a referential (external) for it you can use for enrichment purposes.

Can you have a look at the doc I shared please, to me this was the purpose of the feature.

**Comment by guilhemmarchand** [comment]
Assuming this answered the question, let me know otherwise ;-)
