### ISSUE TITLE
Manual setting of data_max_lag_allowed getting overwritten

### ISSUE THREAD

**Issue by 11gods** [guilhemmarchand/trackme#283]
Hi,
If I set my **trackme_default_host_lag** it appears to be also overwriting my **manual** settings which I put in for **data_max_lag_allowed**

Thanks

**Comment by guilhemmarchand** [comment]
Thank you @11gods , will be reviewed ASAP

**Comment by guilhemmarchand** [comment]
@11gods 

Can you please share the definition you created?

The default is:

<img width="1761" alt="image" src="https://user-images.githubusercontent.com/7503059/110699457-ca371200-81e6-11eb-8834-e0250fac7987.png">

As you can see, there is an if condition:

`eval data_max_lag_allowed=if(isnull(data_max_lag_allowed), "3600", data_max_lag_allowed)`

If you change this to use a different value, you need to keep the if logic, otherwise you will overwrite any custom setting you have set, or policies are defining.

The macro purpose is to define a default value when the host is discovered and added to the collection. (or if for some reasons there wouldn't be a value which is not supposed to happen) 

If you customise this, with the if logic, this will be relevant for newly discovered hosts, or if you reset the collection.

Let me know if my explanation make sense.

My guess is that you are setting an explicit value with no conditions.

**Comment by guilhemmarchand** [comment]
I assume this answered your question @11gods let me know otherwise ;-)
