### ISSUE TITLE
Data Hosts Resetting to Not Monitored

### ISSUE THREAD

**Issue by cidermark** [guilhemmarchand/trackme#284]
Hi Guilhem,

Thanks to your enhancement to allow us to monitor our Splunk estate using the _internal index I enabled 64 of our Splunk servers. Then, when I switched back to Data Sources, there were a load of additional sources that I had deliberately left unmonitored that were now being monitored?!? I have disabled quite a number of these Data Sources and now all of my Splunk estate monitoring has been disabled again!

Is this a behaviour that you would expect? i.e. enabling monitoring on a host enables monitoring of a Data Source?

Cheers,
Mark.

**Comment by guilhemmarchand** [comment]
@cidermark 

Can you provide some screenshots please?
Host monitoring (Splunk host monitoring) is for data hosts and metric hosts, not data sources.

**Comment by cidermark** [comment]
Hi Guilhem, 
Screenshots might be a bit difficult as it would just show an empty screen :) 
Is there a search that I could run that will pull
a) the status of all my Data Sources (name, enabled/disabled) and
b) the status of all my Hosts ( name, enabled/disabled)?
If there is, I could get all my Data Sources back to how I want them, run and export the report. Enable all the Splunk estate hosts and run/export the report. Finally, when the Hosts get disabled again, run the report once more. Hopefully that might shed some light.

It might take me a little while to get my Data Sources back into shape so do you want to 'hold' this for a while and I'll get back to you?

Cheers,
Mark.

**Comment by guilhemmarchand** [comment]
Hi Mark,

I think you are getting confused.

First, let me clarify:

1. All Splunk instances, Universal Forwarders or Heavy Forwarders, are supposed to be forwaring the internals to the indexing layer, this is a proper configuration and good practice configuration.

An example is here: (Splunk PS base config apps)

https://drive.google.com/open?id=107qWrfsv17j5bLxc21ymTagjtHG0AobF

So I don't understand really what means "I enabled 64 of our Splunk servers" for example, this is not clear and can mean anything.

2. There are 3 main concepts in TrackMe:

- data sources
- data hosts
- metric hosts

Each of these have their own definitions for allow list (the indexes you allow TrackMe to be looking at) and the block lists (different options to exclude things you do not want)

There are no interactions between each other.

3. monitored status true or false

An entity, a data source, host or metric host, can be monitored or not, the fields is in the lookups:

- data_monitored_state (for data sources and data hosts)
- metric_monitored_state (for metric hosts)

The 3 lookups and other lookups can be accessed easily via the app nav menu.

These KVstore collections, you can perform bulk updates manually in SPL.

4. Splunk estate monitoring

The new feature does the following:

- When enabled and when the allow list and block lists allow it, in data hosts we take into account "index=_internal sourcetype=splunkd"

- In metric hosts, and if the allow / block list allow it, we take into account the equivalent of the _internal for the metrics, which were introduced by Splunk some versions ago.

There is nothing related at all with data sources.

I do not understand your issues / context because you mixing these altogether.

--> data sources is NOT where monitoring of the Splunk instances happens

--> data host is where you would see the _internal and splunkd, for example:

<img width="1774" alt="image" src="https://user-images.githubusercontent.com/7503059/110977035-8dd7f300-8359-11eb-855d-da417f23614a.png">

**Comment by guilhemmarchand** [comment]
So:

- Explain more clearly your issues at the lights of these explanations

- Review what you expected, review in data sources your allow lists and block lists

- Review in data hosts, not data sources, this where you should see your internal data for the Splunk UF/HF etc

- In addition in data hosts, along with the _internal there will be all the data that TrackMe is allowed to look at

This is quite simple, what appears in TrackMe is what you give TracMe access to

**Comment by guilhemmarchand** [comment]
@cidermark 

Please have a look here:
https://trackme.readthedocs.io/en/testing/monitor_forwarders.html

This will answer your questions regarding the monitoring of Splunk instances forwarding.

**Comment by guilhemmarchand** [comment]
Hi @cidermark 

Any update?
Let me know if you are still running into trouble / confusion.

**Comment by cidermark** [comment]
Hi @guilhemmarchand.

Sorry, I've been off work this week so I've not been able to do anything more on this. I should be back next week so I'll update you then.

Cheers,
Mark.

**Comment by guilhemmarchand** [comment]
@cidermark 
I am assuming you fixes your issues, let me know otherwise.
