### ISSUE TITLE
For the field: "data_monitoring_wdays" is it possible to select the times when we want to monitor it

### ISSUE THREAD

**Issue by 11gods** [guilhemmarchand/trackme#322]
Hi,

I have an application which ingests data only M-F from 8am-5pm

Is it possible to add a new feature in data_monitoring_wdays to allow us to select  a time?

Currently we can select the days only

Thanks

**Comment by guilhemmarchand** [comment]
Hi @11gods 

**I am about to release version 1.2.45 which allows the builtin creation of alerts applying time restrictions:**

![image](https://user-images.githubusercontent.com/7503059/116412873-feb26c00-a82e-11eb-8512-a68625016f9f.png)

Rather than applying hours restrictions on a per data source basis, you could create specific tags for these data sources, then create a custom alert that tracks these data sources.
One could as well simply create alerts tracking these specific data sources while excluding these in the global alert(s).

(Dropdown day time filtering in the screenshot)

Let me know your thinking.

**Comment by guilhemmarchand** [comment]
@11gods 
Version 1.2.45 has been published to address these requirements via alerts and date time filtering.
let me know if you have any questions
