### ISSUE TITLE
data_max_lag_allowed does not change after lagging class is deleted

### ISSUE THREAD

**Issue by TonyY17** [guilhemmarchand/trackme#331]
Hi,
I created a lagging class for the priority of data hosts. This worked fine and the values are shown in the data host overview.
After removing this lagging class, I expected the lag value to change back to the default value, but it does not. The value from the lagging class is still set. Is this expected behaviour?

- Splunk 8.0.6
- SHC in use

Cheers :)

**Comment by guilhemmarchand** [comment]
Hi @TonyY17 

Thanks.
As per the current release, this indeed is the expected behaviour, the explanation is:

- When a lagging class is set and has match, at the next iteration the KVstore field is updated with the max lag value
- During next iterations, this value is preserved
- If in between two iterations, the lagging class is removed, there is no more match, thus the current value is assumed to be the wanted value and preserved

One would need to reset either the host (the reset button or the TrackMe API endpoint via the trackme custom command) or reset the entire collection (which can be annoying as one would loose any priority set and some other settings)

Reading this, I believe it might make sense to review it, your expectation would certainly be the expectations from mist of the users in such a condition.

Will be reviewed thanks
