### ISSUE TITLE
If using allow lists for data sources-alert when new discovered data source is found

### ISSUE THREAD

**Issue by bowesmana** [guilhemmarchand/trackme#348]
The downside of using allow lists is that new data sources will not be discovered and tracked by TrackMe. 

With a continually evolving Splunk deployment there are always new data sources being ingested. If there is an organisational process in place to ensure a critical data source is monitored by TrackMe after being onboarded, that's ok, but it would be useful if TrackMe could support a mode where an alert is created if a new data source is found that would be excluded from tracking due to it not being in the allow list.

Apologies if this can already be achieved, but I could not see how.

**Comment by guilhemmarchand** [comment]
Hi @bowesmana !

Right, I get the point and the potential interest.
However, this might be too much dependent on the customer's context to be implemented as part of the app, but I could address it in the docs.

How about creating this simple alert?

``
| tstats max(_time) as _time, count where (index=* sourcetype=* sourcetype!=stash) by index, sourcetype
| lookup trackme_data_source_monitoring data_index as index, data_sourcetype as sourcetype OUTPUT _key as key
| eval isInTrackMe=if(isnull(key), "false", "true")
| where isInTrackMe=="false"
``

Then get the alert to trigger for every result, and this will let you know that a data source is not in TrackMe due to allow listing.
You might adapt the where condition to your specific context.

Let me know

**Comment by bowesmana** [comment]
Yep, that's a perfect workaround for now - I'm giving a workshop to the client on Monday, so it will help them decide on allow/block implementation.
