### ISSUE TITLE
TrackMe bug report - alert on upper outlier macro not working?

### ISSUE THREAD

**Issue by bl00mberg** [guilhemmarchand/trackme#355]
Hi @guilhemmarchand ,

this "TrackMe Manage and configure" macro configuration seems not working 
![grafik](https://user-images.githubusercontent.com/88150591/128180125-cb10635f-0ad3-4af3-b6bb-20f80b845d15.png)

The configuration remains "false"
![grafik](https://user-images.githubusercontent.com/88150591/128180388-89e3d1f2-5f21-4364-ad58-8c9d6055bfa5.png)

Is this a bug or do I need to run something?
Trackers were already running.

App Version 1.2.47 / 1.2.49

**Comment by guilhemmarchand** [comment]
Hi @bl00mberg 

So I did a verification, at least with latest version (say since 1.2.49) this is working as expected in the meaning that:

- The macro value is used when the entity is discovered and created automatically only
- When the entity exists already, this will not change the existing setting that was used when the entity was discovered
- If the value is set to true, and a new entity created, the UI will indeed show true as this value is the one stored in the KVstore

If you wish to mass update multiple existing entities, I would advise to use SPL for that, something like:

```
| inputlookup trackme_data_source_monitoring | eval keyid=_key
| search data_name="linux_amer:linux_secure"
| eval OutlierAlertOnUpper="true"
| outputlookup append=t key_field=keyid trackme_data_source_monitoring
```

So, to say it differently, the macro values are used when entities are discovered, upon the discovery the settings need to be handled per entity.

Let me know if that makes sense ;-)

Guilhem

**Comment by bl00mberg** [comment]
Hi @guilhemmarchand , 

you are right, this makes more sense this way ;) 
So no unwished config is getting overwritten. 👍 

I'm totally fine with updating by SPL, thanks for the search. :)

**Comment by guilhemmarchand** [comment]
Awesome thanks @bl00mberg !
